language: java
jdk: openjdk8

before_install:
  - ls -la
  - echo $GPG_PASSPHRASE | gpg --import travis.gpg
  - rm -f travis.gpg
  - cp settings.template.xml $HOME/.m2/settings.xml

script:
  - mvn -f modules/json-playback-player-parent/                         clean install
  - mvn -f modules/dummy/                                               clean install
  - mvn -f modules/json-playback-player/                                clean install
  - mvn -f modules/json-playback-player-test/ -P hb3                    clean test
  - mvn -f modules/json-playback-player-test/ -P hb4                    clean test
  - mvn -f modules/json-playback-player-test/ -P hb5                    clean test
  - mvn -f modules/json-playback-player-test/ -P jpa                    clean test
  - mvn -f modules/json-playback-player-test/ -P customized-persistence clean test
    
deploy:
  provider: script
#  script: mvn -P hb3,travis deploy -DskipTests=true && mvn -P hb4,travis deploy -DskipTests=true && mvn -P hb5,travis deploy -DskipTests=true && mvn -P jpa,travis deploy -DskipTests=true && mvn -P jpa,travis deploy -DskipTests=true && mvn -P customized-persistence,travis deploy -DskipTests=true
  script: mvn -f modules/json-playback-player/ -P build-to-dist,travis deploy -DskipTests=true && mvn -f modules/json-playback-player-parent/ -P travis deploy -DskipTests=true
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    condition: $TRAVIS_TAG =~ ^(deploy_.*|publish_.*)$